// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(22)
            {
                { typeof(global::System.Collections.Generic.Dictionary<int, bool>), 0 },
                { typeof(global::System.Collections.Generic.Dictionary<int, float>), 1 },
                { typeof(global::System.Collections.Generic.Dictionary<int, int>), 2 },
                { typeof(global::System.Collections.Generic.List<global::GameServer.Protocol.UserInfo>), 3 },
                { typeof(global::GameServer.SyncCode), 4 },
                { typeof(global::GameServer.Protocol.AnimationData), 5 },
                { typeof(global::GameServer.Protocol.BaseRequest), 6 },
                { typeof(global::GameServer.Protocol.BaseResponse), 7 },
                { typeof(global::GameServer.Protocol.CloseRoomRequest), 8 },
                { typeof(global::GameServer.Protocol.CreateRoomRequest), 9 },
                { typeof(global::GameServer.Protocol.CreateRoomResponse), 10 },
                { typeof(global::GameServer.Protocol.JoinRoomRequest), 11 },
                { typeof(global::GameServer.Protocol.JoinRoomResponse), 12 },
                { typeof(global::GameServer.Protocol.LeaveRoomRequest), 13 },
                { typeof(global::GameServer.Protocol.LeaveRoomResponse), 14 },
                { typeof(global::GameServer.Protocol.LoginRequest), 15 },
                { typeof(global::GameServer.Protocol.LoginResponse), 16 },
                { typeof(global::GameServer.Protocol.ObjectData), 17 },
                { typeof(global::GameServer.Protocol.RoomInfo), 18 },
                { typeof(global::GameServer.Protocol.SyncRequest), 19 },
                { typeof(global::GameServer.Protocol.TransformData), 20 },
                { typeof(global::GameServer.Protocol.UserInfo), 21 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.DictionaryFormatter<int, bool>();
                case 1: return new global::MessagePack.Formatters.DictionaryFormatter<int, float>();
                case 2: return new global::MessagePack.Formatters.DictionaryFormatter<int, int>();
                case 3: return new global::MessagePack.Formatters.ListFormatter<global::GameServer.Protocol.UserInfo>();
                case 4: return new MessagePack.Formatters.GameServer.SyncCodeFormatter();
                case 5: return new MessagePack.Formatters.GameServer.Protocol.AnimationDataFormatter();
                case 6: return new MessagePack.Formatters.GameServer.Protocol.BaseRequestFormatter();
                case 7: return new MessagePack.Formatters.GameServer.Protocol.BaseResponseFormatter();
                case 8: return new MessagePack.Formatters.GameServer.Protocol.CloseRoomRequestFormatter();
                case 9: return new MessagePack.Formatters.GameServer.Protocol.CreateRoomRequestFormatter();
                case 10: return new MessagePack.Formatters.GameServer.Protocol.CreateRoomResponseFormatter();
                case 11: return new MessagePack.Formatters.GameServer.Protocol.JoinRoomRequestFormatter();
                case 12: return new MessagePack.Formatters.GameServer.Protocol.JoinRoomResponseFormatter();
                case 13: return new MessagePack.Formatters.GameServer.Protocol.LeaveRoomRequestFormatter();
                case 14: return new MessagePack.Formatters.GameServer.Protocol.LeaveRoomResponseFormatter();
                case 15: return new MessagePack.Formatters.GameServer.Protocol.LoginRequestFormatter();
                case 16: return new MessagePack.Formatters.GameServer.Protocol.LoginResponseFormatter();
                case 17: return new MessagePack.Formatters.GameServer.Protocol.ObjectDataFormatter();
                case 18: return new MessagePack.Formatters.GameServer.Protocol.RoomInfoFormatter();
                case 19: return new MessagePack.Formatters.GameServer.Protocol.SyncRequestFormatter();
                case 20: return new MessagePack.Formatters.GameServer.Protocol.TransformDataFormatter();
                case 21: return new MessagePack.Formatters.GameServer.Protocol.UserInfoFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name
