// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.GameServer.Protocol
{
    public sealed class TransformDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::GameServer.Protocol.TransformData>
    {
        // ObjectID
        private static global::System.ReadOnlySpan<byte> GetSpan_ObjectID() => new byte[1 + 8] { 168, 79, 98, 106, 101, 99, 116, 73, 68 };
        // Position
        private static global::System.ReadOnlySpan<byte> GetSpan_Position() => new byte[1 + 8] { 168, 80, 111, 115, 105, 116, 105, 111, 110 };
        // EulerAngles
        private static global::System.ReadOnlySpan<byte> GetSpan_EulerAngles() => new byte[1 + 11] { 171, 69, 117, 108, 101, 114, 65, 110, 103, 108, 101, 115 };
        // Scale
        private static global::System.ReadOnlySpan<byte> GetSpan_Scale() => new byte[1 + 5] { 165, 83, 99, 97, 108, 101 };
        // Speed
        private static global::System.ReadOnlySpan<byte> GetSpan_Speed() => new byte[1 + 5] { 165, 83, 112, 101, 101, 100 };

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::GameServer.Protocol.TransformData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value is null)
            {
                writer.WriteNil();
                return;
            }

            var formatterResolver = options.Resolver;
            writer.WriteMapHeader(5);
            writer.WriteRaw(GetSpan_ObjectID());
            writer.Write(value.ObjectID);
            writer.WriteRaw(GetSpan_Position());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<UnityEngine.Vector3>(formatterResolver).Serialize(ref writer, value.Position, options);
            writer.WriteRaw(GetSpan_EulerAngles());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<UnityEngine.Vector3>(formatterResolver).Serialize(ref writer, value.EulerAngles, options);
            writer.WriteRaw(GetSpan_Scale());
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<UnityEngine.Vector3>(formatterResolver).Serialize(ref writer, value.Scale, options);
            writer.WriteRaw(GetSpan_Speed());
            writer.Write(value.Speed);
        }

        public global::GameServer.Protocol.TransformData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            var formatterResolver = options.Resolver;
            var length = reader.ReadMapHeader();
            var ____result = new global::GameServer.Protocol.TransformData();

            for (int i = 0; i < length; i++)
            {
                var stringKey = global::MessagePack.Internal.CodeGenHelpers.ReadStringSpan(ref reader);
                switch (stringKey.Length)
                {
                    default:
                    FAIL:
                      reader.Skip();
                      continue;
                    case 8:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 4920592038131032655UL:
                                ____result.ObjectID = reader.ReadInt32();
                                continue;
                            case 7957695015293251408UL:
                                ____result.Position = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<UnityEngine.Vector3>(formatterResolver).Deserialize(ref reader, options);
                                continue;
                        }
                    case 11:
                        if (!global::System.MemoryExtensions.SequenceEqual(stringKey, GetSpan_EulerAngles().Slice(1))) { goto FAIL; }

                        ____result.EulerAngles = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<UnityEngine.Vector3>(formatterResolver).Deserialize(ref reader, options);
                        continue;
                    case 5:
                        switch (global::MessagePack.Internal.AutomataKeyGen.GetKey(ref stringKey))
                        {
                            default: goto FAIL;
                            case 435610018643UL:
                                ____result.Scale = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<UnityEngine.Vector3>(formatterResolver).Deserialize(ref reader, options);
                                continue;
                            case 431197876307UL:
                                ____result.Speed = reader.ReadSingle();
                                continue;
                        }

                }
            }

            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
